apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-eventbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhbw-eventbus
  template:
    metadata:
      labels:
        app: dhbw-eventbus
    spec:
      containers:
        - image: replace/me/event-bus
          name: dhbw-eventbus
          env:
            - name: EVENTBUS_HOST
              value: "dhbw-eventbus"
            - name: EVENTBUS_PORT
              value: "4000"
            - name: DISPLAYDATA_HOST
              value: "dhbw-displaydata"
            - name: DISPLAYDATA_PORT
              value: "3000"