apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhbw-eventbus
    app.kubernetes.io/component: dhbw-eventbus
    app.kubernetes.io/instance: dhbw-eventbus
    app.kubernetes.io/part-of: dhbw-micro
  name: dhbw-eventbus
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dhbw-eventbus
    deploymentconfig: dhbw-eventbus
  sessionAffinity: None
  type: ClusterIP
