apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhbw-eventbus
  name: dhbw-eventbus
spec:
  ports:
  - name: eventbus-port
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: dhbw-eventbus
  type: ClusterIP
