apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-receivedata
spec:
  # Create X pods (replicas) to load balance by ingress
  replicas: 1
  selector:
    matchLabels:
      app: dhbw-receivedata
  template:
    metadata:
      labels:
        app: dhbw-receivedata
    spec:
      containers:
        - image: replace/me/receivedata
          imagePullPolicy: Always
          name: dhbw-receivedata
          resources:
            # limit to 128 MB and 1 core
            # not *technically* 128MB but 128 Mebibyte, but close enough...
            limits:
              memory: "128Mi"
              cpu: "1"
          env:
            - name: RECEIVEDATA_HOST
              value: "dhbw-receivedata"
            - name: RECEIVEDATA_PORT
              value: "4001"
            - name: EVENTBUS_HOST
              value: "dhbw-eventbus"
            - name: EVENTBUS_PORT
              value: "4000"
          livenessProbe:
            httpGet:
              path: /values
              port: 4001
            initialDelaySeconds: 3
            periodSeconds: 10