apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dhbw-receivedata
spec:
  rules:
    - host: dhbw-micro.info
      http:
        paths:
          - path: /receivedata
            pathType: Prefix
            backend:
              serviceName: dhbw-receivedata
              servicePort: 4001
