apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dhbw-receivedata
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: dhbw-receivedata
              servicePort: 4001