apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhbw-receivedata
  name: dhbw-receivedata
spec:
  ports:
  - name: receivedata-port
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: dhbw-receivedata
  type: NodePort
