apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhbw-mongodb
  template:
    metadata:
      labels:
        app: dhbw-mongodb
    spec:
      containers:
        - image: replace/me/mongodb
          name: dhbw-mongodb
          env:
            - name: MONGO_INITDB_HOST
              value: "dhbw-mongodb"
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_DATABASE
              value: "co2Ampel"
            - name: MONGO_INITDB_USERNAME
              value: 'test'
            - name: MONGO_INITDB_PASSWORD
              value: 'test'
          # Volume mounts for persistent store and initdb script
          volumeMounts:
            - name: mongodb-store
              mountPath: /data/mongodb
            - name: mongodb-init
              mountPath: /docker-entrypoint-initdb.d
      # volume + claim
      volumes:
        - name: mongodb-store
          persistentVolumeClaim:
            claimName: mongodb-claim
        - name: mongodb-init
          configMap:
            name: mongodb-init
            defaultMode: 0744