apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhbw-mongodb
  template:
    metadata:
      labels:
        app: dhbw-mongodb
    spec:
      containers:
        - image: replace/me/mongodb
          name: dhbw-mongodb
          env:
            - name: MONGO_INITDB_HOST
              value: "localhost"
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_NAME
              value: "co2Ampel"
            - name: MONGO_INITDB_USER
              value: "test"
            - name: MONGO_INITDB_PASS
              value: "test"