apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-displaydata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhbw-displaydata
  template:
    metadata:
      labels:
        app: dhbw-displaydata
    spec:
      containers:
        - image: replace/me/displaydata
          name: dhbw-displaydata
          env:
            - name: DISPLAYDATA_HOST
              value: "dhbw-displaydata"
            - name: DISPLAYDATA_PORT
              value: "3000"
            - name: MONGO_INITDB_HOST
              value: "dhbw-mongodb"
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_NAME
              value: "co2Ampel"
            - name: MONGO_INITDB_USER
              value: "test"
            - name: MONGO_INITDB_PASS
              value: "test"