apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dhbw-displaydata
spec:
  rules:
    - host: dhbw-micro.info
      http:
        paths:
          - path: /eventbus
            pathType: Prefix
            backend:
              serviceName: dhbw-displaydata
              servicePort: 3000