apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhbw-displaydata
  name: dhbw-displaydata
spec:
  ports:
  - name: displaydata-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dhbw-displaydata
  type: NodePort
